title: Home
email: zszhong@link.cuhk.edu.hk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Zhisheng Zhong # add your name
author-pic: portrait.jpg
about-author: .

# Contact links
email: zszhong@link.cuhk.edu.hk # Add your Email address
phone: xxxxxxxxxx # Add your Phone number
website: zhishengzhong.com # Add your website, do not add http://
# linkedin: chenyilun95 # Add your Linkedin handle
github: zs-zhong # Add your Github handle
# twitter: '@chenyilun95' #'@artemsheludko_' # Add your Twitter handle
# facebook: '@chenyilun95' # Add your Facebook handle
# instagram: '@chenyilun95' # Add your Instagram handle
# pinterest: '@chenyilun95' # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

